# Generated by Django 2.2.1 on 2019-05-26 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='on_post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='on',
        ),
        migrations.RemoveField(
            model_name='share',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='share',
            name='shared_post',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='core.Comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='shares',
            field=models.ManyToManyField(to='core.Share'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('post_like', 'Liked a post'), ('post_comment', 'Commented on post'), ('post_share', 'Shared a post'), ('friend_request', 'Recieved a friend request')], max_length=15)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
