# Generated by Django 2.2.1 on 2019-05-26 10:27

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20190526_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='dps/profile.jpg', null=True, upload_to=authentication.models.custom_upload_url),
        ),
    ]
